// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';

export function AcceptFileTransfer(arg1:string):Promise<void>;

export function GetFileOffersHistory(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<db.FileOfferRecord>>;

export function GetInitialState():Promise<main.InitialState>;

export function GetMessageHistory(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<db.MessageRecord>>;

export function MinimizeToTray():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function RejectFileTransfer(arg1:string):Promise<void>;

export function SelectAndSendFile(arg1:string):Promise<string>;

export function SendChatMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendPing(arg1:string):Promise<void>;

export function SetNickname(arg1:string):Promise<boolean>;
