// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFileTransfer(arg1:string):Promise<void>;

export function GetInitialState():Promise<main.InitialState>;

export function RejectFileTransfer(arg1:string):Promise<void>;

export function SelectAndSendFile(arg1:string):Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SendPing(arg1:string):Promise<void>;

export function SetNickname(arg1:string):Promise<boolean>;

export function ShowNativeNotification(arg1:string,arg2:string):Promise<void>;
